#!/bin/bash

PHPSysConfig=`php -i | grep /php.ini | awk '{print $5}'`;

# Copy the `php.ini` from current php cli.
cp -f $PHPSysConfig /tmp/php.ini

# Append `custom.php`.ini into `php.ini`
cat env/custom.php.ini >> /tmp/php.ini

# Run server with the appended `php.ini`
php -c /tmp/php.ini -S localhost:8000 -t public
